### ISSUE TITLE
force Videotype to 360

### ISSUE THREAD

**Issue by tomabg** [picoxr/launch-pico-player#2]
Hi,

i just trying to play a 2d mp4 and it work perfect.
However i tried to force playing it as 360 video but its always started in Mode 2D.

Code:
val Picoplayer : PicovrLaunchPlayer =  PicovrLaunchPlayer()
Picoplayer.launchVideoPlayer(context , downloaddir.toString() + File.separator, filenametest ,"2")

My VR Headset SW version is:
C086_RF01_BV2.0.1_SV1.90_20200117_B226

And one more question:
How to access the pano Modes in the built in playxer?

Any help would be welcome.

Thanks
Thomas

**Comment by picoxr** [comment]
Hi Thomas,

Have you tried to open the video in File Manager with the built-in Video player? Will it be played in 360? And have you tried to change the play mode in the built-in player? 
Besides, could you please send us the video for testing? 

For further negociation, please send email to our technical support mailbox - support.tob@picovr.com.

Dragon

**Comment by tomabg** [comment]
Hi Dragon,


Find attached the Video i used.

I can open Video with filemanager and it is played in the 2D mode.

I can change mode inside the built-in player and it works.

What I want is to give the mode in the launchintent like this:
launchintent.putExtra("videoType", "2")

…or using your class with:
val Picoplayer : PicovrLaunchPlayer =  PicovrLaunchPlayer()
Picoplayer.launchVideoPlayer(context , downloaddir.toString() + File.separator, filename ,"2")

This always starts buil in Player with mode 2D.

So it Looks like videoType is ignored by the built-in player.

If needed i can send you my playvideo function(kotlin).

BR
Thomas


Gesendet von Mail für Windows 10

Von: Pico
Gesendet: Donnerstag, 12. März 2020 07:32
An: picoxr/launch-pico-player
Cc: tomabg; Author
Betreff: Re: [picoxr/launch-pico-player] force Videotype to 360 (#2)

Hi Thomas,
Have you tried to open the video in File Manager with the built-in Video player? Will it be played in 360? And have you tried to change the play mode in the built-in player?
Besides, could you please send us the video for testing?
For further negociation, please send email to our technical support mailbox - support.tob@picovr.com.
Dragon

**Comment by picoxr** [comment]
Hi Thomas,

The bug you mentioned was found after our testing. It has been fixed in the Pico Video player which will be available in the next OTA. If you need it urgently, we can provide you the latest APK file.

If any further questions, please send an email to our technical support mailbox - support.tob@picovr.com.

Licky

**Comment by tomabg** [comment]
Hi,

for a test can you send me the apk please.

thanks
Thomas

Von: Pico
Gesendet: Freitag, 13. März 2020 13:58
An: picoxr/launch-pico-player
Cc: tomabg; Author
Betreff: Re: [picoxr/launch-pico-player] force Videotype to 360 (#2)

Hi Thomas,
The bug you mentioned was found after our testing. It has been fixed in the Pico Video player which will be available in the next OTA. If you need it urgently, we can provide you the latest APK file.
If any further questions, please send an email to our technical support mailbox - support.tob@picovr.com.
Licky

**Comment by picoxr** [comment]
Hi Thomas,

Please download it from the URL.
https://drive.google.com/open?id=1RXv8cqRJkQeaLmFKIkt8ixEuqVDSO_dn

If any further questions, please send an email to our technical support mailbox - support.tob@picovr.com.
Licky

**Comment by tomabg** [comment]
any version info when this will be released?

t the moment i am unable to test is because of corona restictions:-)

**Comment by dragongyke** [comment]
Hi Tomabg, this is Dragon from Pico support team, may I know your email address for further discussion?
