### ISSUE TITLE
isPlayEndAndClose not working

### ISSUE THREAD

**Issue by DrewDahlman** [picoxr/launch-pico-player#3]
I've modified the JAR to allow the `isPlayEndAndClose` extra along with others. Everything else seems to be working fine but when the video completes it doesn't exit. 

Here's my `launchVideoPlayer`

```java
public void launchVideoPlayer(String videoPath, String videoName, String videoType) {
		String path = videoPath + videoName;
		Log.e(TAG, "path = " + path);
		Intent intent = new Intent();
		intent.setAction(action);
		intent.putExtra("title", videoName);
		intent.putExtra("uri", Uri.fromFile(new File(path)).toString());
		intent.putExtra("videoType", videoType);
		intent.putExtra("seekPlay", false);
		intent.putExtra("loop", false);
		intent.putExtra("isPlayEndAndClose", true);
		intent.putExtra("isSingplePlayLoop", false);
		intent.putExtra("isControl", false);
		startActivity(intent);
}
```

When the video loads I see the settings reflected:

I have the activity set to `com.picovr.picoplaymanager.PicovrPlayManagerActivity`

```xml
<activity android:name="com.picovr.picoplaymanager.PicovrPlayManagerActivity" android:label="@string/app_name" android:screenOrientation="landscape" android:launchMode="singleTask" android:configChanges="screenSize|orientation|keyboardHidden|keyboard">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
</activity>
```

When I expose the controls exit works fine and returns to my app, but when I try to auto close it just freezes.

**Comment by picoxr** [comment]
What is the PUI version of the device you are using?If it is below PUI 3.6.0, please install APK in the link and try again.
https://drive.google.com/file/d/1ka7SbfWyP-h3QNoHOIdigsYbOwW7_kDG/view?usp=sharing

**Comment by picoxr** [comment]
What type of devices are you using?This approach supports G2 4K,Neo 2,but not G2.

**Comment by DrewDahlman** [comment]
This is a G2 4K S device

**Comment by picoxr** [comment]
The "loop" parameter should be "Loop". This is a mistake in our doc, sorry for the inconvenience and it has be updated. 
And there is an extra letter "p" in the "isSingplePlayLoop", it defaults to false, thus it is unnecessary for your needs.

**Comment by DrewDahlman** [comment]
Yep I discovered the loop after much trial and error as well as the mistake in the singlePlayLoop!

Thanks!
